import '../models/product.dart';
import '../models/category.dart';

class ProductService {
  static List<Category> getCategories() {
    return [
      Category(
        id: '1',
        name: 'Kebutuhan Rumah Tangga',
        icon: '🏠',
        description: 'Produk kebutuhan rumah tangga lengkap',
      ),
      Category(
        id: '2',
        name: 'Bumbu Dapur',
        icon: '🌶️',
        description: 'Bumbu dan rempah-rempah pilihan',
      ),
      Category(
        id: '3',
        name: 'Snack',
        icon: '🍿',
        description: 'Aneka snack dan camilan lezat',
      ),
      Category(
        id: '4',
        name: 'Minuman',
        icon: '🥤',
        description: 'Berbagai pilihan minuman segar',
      ),
      Category(
        id: '5',
        name: 'Roti & Bakery',
        icon: '🍞',
        description: 'Roti segar dan produk bakery',
      ),
      Category(
        id: '6',
        name: 'Rokok',
        icon: '🚬',
        description: 'Koleksi rokok berbagai merek',
      ),
      Category(
        id: '7',
        name: 'Shampo & Kondisioner',
        icon: '🧴',
        description: 'Produk perawatan rambut terbaik',
      ),
      Category(
        id: '8',
        name: 'Sabun & Body Care',
        icon: '🧼',
        description: 'Sabun dan perawatan tubuh',
      ),
      Category(
        id: '9',
        name: 'Alat Kecantikan',
        icon: '💄',
        description: 'Peralatan dan produk kecantikan',
      ),
    ];
  }

  static List<Product> getDummyProducts() {
    return [
      // KATEGORI 1: Kebutuhan Rumah Tangga (15 produk)
      Product(
        id: '1',
        name: 'Sabun Cuci Piring Sunlight 800ml',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 12500,
        description: 'Sabun cuci piring yang efektif membersihkan lemak membandel',
        imageUrl:
            'https://images.pexels.com/photos/3962286/pexels-photo-3962286.jpeg',
        rating: 4.5,
        reviews: 248,
        stock: 50,
      ),
      Product(
        id: '2',
        name: 'Deterjen Rinso 1kg',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 18000,
        description: 'Deterjen cair untuk mesin cuci dan cuci tangan',
        imageUrl:
            'https://images.pexels.com/photos/6477518/pexels-photo-6477518.jpeg',
        rating: 4.7,
        reviews: 512,
        stock: 45,
      ),
      Product(
        id: '3',
        name: 'Pembersih Lantai Dettol 750ml',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 22000,
        description: 'Pembersih lantai dengan daya bunuh kuman tinggi',
        imageUrl:
            'https://images.pexels.com/photos/2906632/pexels-photo-2906632.jpeg',
        rating: 4.6,
        reviews: 189,
        stock: 35,
      ),
      Product(
        id: '4',
        name: 'Tisu Kembang Pasir 4ply 16roll',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 48000,
        description: 'Tisu premium 4 ply dengan kelembutan maksimal',
        imageUrl:
            'https://images.pexels.com/photos/3994623/pexels-photo-3994623.jpeg',
        rating: 4.8,
        reviews: 678,
        stock: 100,
      ),
      Product(
        id: '5',
        name: 'Kain Lap Microfiber 5 pcs',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 35000,
        description: 'Kain lap microfiber untuk membersihkan tanpa meninggalkan serat',
        imageUrl:
            'https://images.pexels.com/photos/3962283/pexels-photo-3962283.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 60,
      ),
      Product(
        id: '6',
        name: 'Penghapus Noda Vanish 500ml',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 28000,
        description: 'Penghapus noda efektif untuk pakaian putih dan berwarna',
        imageUrl:
            'https://images.pexels.com/photos/3962287/pexels-photo-3962287.jpeg',
        rating: 4.5,
        reviews: 234,
        stock: 40,
      ),
      Product(
        id: '7',
        name: 'Pengharum Ruangan Aer Spray 400ml',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 15000,
        description: 'Pengharum ruangan dengan aroma segar tahan lama',
        imageUrl:
            'https://images.pexels.com/photos/7234527/pexels-photo-7234527.jpeg',
        rating: 4.3,
        reviews: 145,
        stock: 80,
      ),
      Product(
        id: '8',
        name: 'Sapu Lidi Premium Jumbo',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 42000,
        description: 'Sapu lidi premium dengan desain ergonomis',
        imageUrl:
            'https://images.pexels.com/photos/3962281/pexels-photo-3962281.jpeg',
        rating: 4.6,
        reviews: 198,
        stock: 30,
      ),
      Product(
        id: '9',
        name: 'Ember Plastik 20L',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 35000,
        description: 'Ember plastik berkualitas untuk berbagai keperluan',
        imageUrl:
            'https://images.pexels.com/photos/3962284/pexels-photo-3962284.jpeg',
        rating: 4.4,
        reviews: 123,
        stock: 55,
      ),
      Product(
        id: '10',
        name: 'Sikat WC Dengan Holder',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 18000,
        description: 'Sikat WC berkualitas dengan holder yang kokoh',
        imageUrl:
            'https://images.pexels.com/photos/3962282/pexels-photo-3962282.jpeg',
        rating: 4.5,
        reviews: 89,
        stock: 70,
      ),
      Product(
        id: '11',
        name: 'Kayu Jemuran 3 Tali',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 52000,
        description: 'Kayu jemuran berkualitas dengan konstruksi kuat',
        imageUrl:
            'https://images.pexels.com/photos/3962285/pexels-photo-3962285.jpeg',
        rating: 4.7,
        reviews: 267,
        stock: 25,
      ),
      Product(
        id: '12',
        name: 'Kuas Cuci Piring Set 3 Pcs',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 22000,
        description: 'Kuas cuci piring dengan bulu lembut dan tahan lama',
        imageUrl:
            'https://images.pexels.com/photos/3962288/pexels-photo-3962288.jpeg',
        rating: 4.3,
        reviews: 145,
        stock: 65,
      ),
      Product(
        id: '13',
        name: 'Pembuang Sampah Stainless 20L',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 85000,
        description: 'Tempat sampah stainless dengan desain modern',
        imageUrl:
            'https://images.pexels.com/photos/3962289/pexels-photo-3962289.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 15,
      ),
      Product(
        id: '14',
        name: 'Gantungan Baju Plastik 5 Pcs',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 28000,
        description: 'Gantungan baju dengan desain anti slip',
        imageUrl:
            'https://images.pexels.com/photos/3962290/pexels-photo-3962290.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 90,
      ),
      Product(
        id: '15',
        name: 'Kotak Penyimpanan Plastik 30L',
        categoryId: '1',
        categoryName: 'Kebutuhan Rumah Tangga',
        price: 65000,
        description: 'Kotak penyimpanan dengan daya tampung besar',
        imageUrl:
            'https://images.pexels.com/photos/3962291/pexels-photo-3962291.jpeg',
        rating: 4.5,
        reviews: 234,
        stock: 40,
      ),

      // KATEGORI 2: Bumbu Dapur (15 produk)
      Product(
        id: '16',
        name: 'Garam Himalaya 500gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 25000,
        description: 'Garam Himalaya premium untuk memasak',
        imageUrl:
            'https://images.pexels.com/photos/5732481/pexels-photo-5732481.jpeg',
        rating: 4.6,
        reviews: 312,
        stock: 60,
      ),
      Product(
        id: '17',
        name: 'Merica Bubuk 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 18000,
        description: 'Merica bubuk dengan aroma kuat dan tajam',
        imageUrl:
            'https://images.pexels.com/photos/3956319/pexels-photo-3956319.jpeg',
        rating: 4.5,
        reviews: 189,
        stock: 50,
      ),
      Product(
        id: '18',
        name: 'Bawang Putih Bubuk 50gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 12000,
        description: 'Bawang putih bubuk praktis untuk memasak',
        imageUrl:
            'https://images.pexels.com/photos/6298298/pexels-photo-6298298.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 75,
      ),
      Product(
        id: '19',
        name: 'Kunyit Bubuk 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 14000,
        description: 'Kunyit bubuk berkualitas tinggi',
        imageUrl:
            'https://images.pexels.com/photos/3728162/pexels-photo-3728162.jpeg',
        rating: 4.5,
        reviews: 134,
        stock: 65,
      ),
      Product(
        id: '20',
        name: 'Kayu Manis 50gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 22000,
        description: 'Kayu manis pilihan untuk rempah lengkap',
        imageUrl:
            'https://images.pexels.com/photos/3728163/pexels-photo-3728163.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 40,
      ),
      Product(
        id: '21',
        name: 'Pala Bubuk 50gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 20000,
        description: 'Pala bubuk dengan aroma hangat dan nikmat',
        imageUrl:
            'https://images.pexels.com/photos/3728164/pexels-photo-3728164.jpeg',
        rating: 4.5,
        reviews: 145,
        stock: 35,
      ),
      Product(
        id: '22',
        name: 'Lada Hitam 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 28000,
        description: 'Lada hitam premium dengan rasa kuat',
        imageUrl:
            'https://images.pexels.com/photos/3728165/pexels-photo-3728165.jpeg',
        rating: 4.7,
        reviews: 267,
        stock: 45,
      ),
      Product(
        id: '23',
        name: 'Cengkeh 50gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 32000,
        description: 'Cengkeh berkualitas untuk bumbu masakan',
        imageUrl:
            'https://images.pexels.com/photos/3728166/pexels-photo-3728166.jpeg',
        rating: 4.6,
        reviews: 189,
        stock: 30,
      ),
      Product(
        id: '24',
        name: 'Ketumbar Biji 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 18000,
        description: 'Ketumbar biji asli untuk bumbu tradisional',
        imageUrl:
            'https://images.pexels.com/photos/3728167/pexels-photo-3728167.jpeg',
        rating: 4.4,
        reviews: 123,
        stock: 55,
      ),
      Product(
        id: '25',
        name: 'Kumis Kucing Kering 50gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 16000,
        description: 'Kumis kucing kering untuk obat herbal',
        imageUrl:
            'https://images.pexels.com/photos/3728168/pexels-photo-3728168.jpeg',
        rating: 4.3,
        reviews: 98,
        stock: 40,
      ),
      Product(
        id: '26',
        name: 'Lengkuas 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 15000,
        description: 'Lengkuas kering berkualitas tinggi',
        imageUrl:
            'https://images.pexels.com/photos/3728169/pexels-photo-3728169.jpeg',
        rating: 4.5,
        reviews: 156,
        stock: 50,
      ),
      Product(
        id: '27',
        name: 'Asam Jawa 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 12000,
        description: 'Asam jawa asli untuk rasa masakan',
        imageUrl:
            'https://images.pexels.com/photos/3728170/pexels-photo-3728170.jpeg',
        rating: 4.4,
        reviews: 134,
        stock: 65,
      ),
      Product(
        id: '28',
        name: 'Biji Fenugreek 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 24000,
        description: 'Biji fenugreek untuk bumbu kari',
        imageUrl:
            'https://images.pexels.com/photos/3728171/pexels-photo-3728171.jpeg',
        rating: 4.5,
        reviews: 167,
        stock: 38,
      ),
      Product(
        id: '29',
        name: 'Jintan Hitam 100gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 26000,
        description: 'Jintan hitam untuk bumbu masakan tradisional',
        imageUrl:
            'https://images.pexels.com/photos/3728172/pexels-photo-3728172.jpeg',
        rating: 4.6,
        reviews: 198,
        stock: 42,
      ),
      Product(
        id: '30',
        name: 'Anise Bintang 50gr',
        categoryId: '2',
        categoryName: 'Bumbu Dapur',
        price: 28000,
        description: 'Anise bintang untuk bumbu masakan Asia',
        imageUrl:
            'https://images.pexels.com/photos/3728173/pexels-photo-3728173.jpeg',
        rating: 4.5,
        reviews: 145,
        stock: 35,
      ),

      // KATEGORI 3: Snack (15 produk)
      Product(
        id: '31',
        name: 'Keripik Singkong Rasa Balado 200gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 18000,
        description: 'Keripik singkong renyah dengan rasa balado pedas',
        imageUrl:
            'https://images.pexels.com/photos/5837452/pexels-photo-5837452.jpeg',
        rating: 4.6,
        reviews: 456,
        stock: 100,
        isPromo: true,
        promoPrice: 14000,
      ),
      Product(
        id: '32',
        name: 'Seaweed Snack 60gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 22000,
        description: 'Rumput laut kering dengan rasa gurih',
        imageUrl:
            'https://images.pexels.com/photos/5836763/pexels-photo-5836763.jpeg',
        rating: 4.7,
        reviews: 234,
        stock: 80,
      ),
      Product(
        id: '33',
        name: 'Cemilan Kacang Asin 150gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 15000,
        description: 'Kacang asin berkualitas dengan rasa sempurna',
        imageUrl:
            'https://images.pexels.com/photos/5836764/pexels-photo-5836764.jpeg',
        rating: 4.5,
        reviews: 312,
        stock: 90,
      ),
      Product(
        id: '34',
        name: 'Cookies Coklat Lezat 200gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 25000,
        description: 'Cookies dengan lelehan coklat yang nikmat',
        imageUrl:
            'https://images.pexels.com/photos/5836765/pexels-photo-5836765.jpeg',
        rating: 4.6,
        reviews: 189,
        stock: 60,
      ),
      Product(
        id: '35',
        name: 'Popcorn Caramel Butter 100gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 20000,
        description: 'Popcorn dengan lapisan karamel dan butter',
        imageUrl:
            'https://images.pexels.com/photos/5836766/pexels-photo-5836766.jpeg',
        rating: 4.5,
        reviews: 267,
        stock: 75,
      ),
      Product(
        id: '36',
        name: 'Pillow Snack Coklat 120gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 18000,
        description: 'Snack empuk dengan rasa coklat yang creamy',
        imageUrl:
            'https://images.pexels.com/photos/5836767/pexels-photo-5836767.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 70,
      ),
      Product(
        id: '37',
        name: 'Kerupuk Udang Tradisional 200gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 22000,
        description: 'Kerupuk udang asli dengan rasa gurih',
        imageUrl:
            'https://images.pexels.com/photos/5836768/pexels-photo-5836768.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 55,
      ),
      Product(
        id: '38',
        name: 'Kacang Mete Panggang 150gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 35000,
        description: 'Kacang mete pilihan dengan tekstur renyah',
        imageUrl:
            'https://images.pexels.com/photos/5836769/pexels-photo-5836769.jpeg',
        rating: 4.7,
        reviews: 234,
        stock: 40,
      ),
      Product(
        id: '39',
        name: 'Marshmallow Putih 100gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 16000,
        description: 'Marshmallow empuk dan lezat',
        imageUrl:
            'https://images.pexels.com/photos/5836770/pexels-photo-5836770.jpeg',
        rating: 4.5,
        reviews: 145,
        stock: 85,
      ),
      Product(
        id: '40',
        name: 'Pretzel Asin 150gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 19000,
        description: 'Pretzel renyah dengan rasa asin sempurna',
        imageUrl:
            'https://images.pexels.com/photos/5836771/pexels-photo-5836771.jpeg',
        rating: 4.4,
        reviews: 123,
        stock: 60,
      ),
      Product(
        id: '41',
        name: 'Wafer Coklat Lapis 200gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 21000,
        description: 'Wafer berlapis coklat dengan rasa istimewa',
        imageUrl:
            'https://images.pexels.com/photos/5836772/pexels-photo-5836772.jpeg',
        rating: 4.5,
        reviews: 167,
        stock: 50,
      ),
      Product(
        id: '42',
        name: 'Biscuit Coklat 250gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 24000,
        description: 'Biscuit renyah dengan topping coklat',
        imageUrl:
            'https://images.pexels.com/photos/5836773/pexels-photo-5836773.jpeg',
        rating: 4.6,
        reviews: 198,
        stock: 65,
      ),
      Product(
        id: '43',
        name: 'Gummy Bear Warna Warni 100gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 17000,
        description: 'Permen gummy dengan berbagai rasa buah',
        imageUrl:
            'https://images.pexels.com/photos/5836774/pexels-photo-5836774.jpeg',
        rating: 4.5,
        reviews: 234,
        stock: 95,
      ),
      Product(
        id: '44',
        name: 'Jagung Kupas Gurih 100gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 14000,
        description: 'Jagung kupas dengan bumbu gurih lezat',
        imageUrl:
            'https://images.pexels.com/photos/5836775/pexels-photo-5836775.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 80,
      ),
      Product(
        id: '45',
        name: 'Roti Tawar Mini 200gr',
        categoryId: '3',
        categoryName: 'Snack',
        price: 23000,
        description: 'Roti tawar mini yang lembut',
        imageUrl:
            'https://images.pexels.com/photos/5836776/pexels-photo-5836776.jpeg',
        rating: 4.5,
        reviews: 189,
        stock: 45,
      ),

      // KATEGORI 4: Minuman (15 produk)
      Product(
        id: '46',
        name: 'Coca Cola Botol 1.5L',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 18000,
        description: 'Minuman soda cola yang menyegarkan',
        imageUrl:
            'https://images.pexels.com/photos/3957984/pexels-photo-3957984.jpeg',
        rating: 4.6,
        reviews: 567,
        stock: 120,
      ),
      Product(
        id: '47',
        name: 'Sprite Botol 1.5L',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 16000,
        description: 'Minuman soda lemon yang segar dan ringan',
        imageUrl:
            'https://images.pexels.com/photos/3957985/pexels-photo-3957985.jpeg',
        rating: 4.5,
        reviews: 423,
        stock: 100,
      ),
      Product(
        id: '48',
        name: 'Fanta Orange 1.5L',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 16000,
        description: 'Minuman soda rasa jeruk yang lezat',
        imageUrl:
            'https://images.pexels.com/photos/3957986/pexels-photo-3957986.jpeg',
        rating: 4.5,
        reviews: 389,
        stock: 110,
      ),
      Product(
        id: '49',
        name: 'Teh Botol Sosro 500ml',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 8000,
        description: 'Teh hitam yang nikmat dan menyegarkan',
        imageUrl:
            'https://images.pexels.com/photos/3957987/pexels-photo-3957987.jpeg',
        rating: 4.7,
        reviews: 678,
        stock: 200,
      ),
      Product(
        id: '50',
        name: 'Es Teh Sosro 1L',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 12000,
        description: 'Es teh yang segar dan lembab',
        imageUrl:
            'https://images.pexels.com/photos/3957988/pexels-photo-3957988.jpeg',
        rating: 4.6,
        reviews: 456,
        stock: 150,
      ),
      Product(
        id: '51',
        name: 'Jus Jeruk Murni 1L',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 22000,
        description: 'Jus jeruk segar tanpa pemanis buatan',
        imageUrl:
            'https://images.pexels.com/photos/3957989/pexels-photo-3957989.jpeg',
        rating: 4.6,
        reviews: 267,
        stock: 80,
      ),
      Product(
        id: '52',
        name: 'Kopi Instan Nescafe 50gr',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 28000,
        description: 'Kopi instan dengan rasa kuat dan nikmat',
        imageUrl:
            'https://images.pexels.com/photos/3957990/pexels-photo-3957990.jpeg',
        rating: 4.7,
        reviews: 345,
        stock: 95,
      ),
      Product(
        id: '53',
        name: 'Susu Cair Frisian Flag 1L',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 32000,
        description: 'Susu segar yang bergizi lengkap',
        imageUrl:
            'https://images.pexels.com/photos/3957991/pexels-photo-3957991.jpeg',
        rating: 4.6,
        reviews: 234,
        stock: 70,
      ),
      Product(
        id: '54',
        name: 'Yogurt Cair Yakult 100ml x 5',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 25000,
        description: 'Yogurt probiotik yang menyehatkan',
        imageUrl:
            'https://images.pexels.com/photos/3957992/pexels-photo-3957992.jpeg',
        rating: 4.7,
        reviews: 389,
        stock: 120,
      ),
      Product(
        id: '55',
        name: 'Minuman Isotonik Pocari Sweat 500ml',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 12000,
        description: 'Minuman isotonik untuk rehidrasi',
        imageUrl:
            'https://images.pexels.com/photos/3957993/pexels-photo-3957993.jpeg',
        rating: 4.5,
        reviews: 289,
        stock: 150,
      ),
      Product(
        id: '56',
        name: 'Vitamin C Effervescent 10 Tablet',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 15000,
        description: 'Vitamin C untuk meningkatkan imun',
        imageUrl:
            'https://images.pexels.com/photos/3957994/pexels-photo-3957994.jpeg',
        rating: 4.6,
        reviews: 198,
        stock: 100,
      ),
      Product(
        id: '57',
        name: 'Susu Kental Manis Kondensasi 1kg',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 24000,
        description: 'Susu kental manis premium',
        imageUrl:
            'https://images.pexels.com/photos/3957995/pexels-photo-3957995.jpeg',
        rating: 4.5,
        reviews: 267,
        stock: 85,
      ),
      Product(
        id: '58',
        name: 'Air Mineral Aqua 500ml x 12',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 35000,
        description: 'Air mineral kemasan praktis',
        imageUrl:
            'https://images.pexels.com/photos/3957996/pexels-photo-3957996.jpeg',
        rating: 4.7,
        reviews: 456,
        stock: 180,
      ),
      Product(
        id: '59',
        name: 'Teh Tarik Bubuk 500gr',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 22000,
        description: 'Teh tarik bubuk yang praktis',
        imageUrl:
            'https://images.pexels.com/photos/3957997/pexels-photo-3957997.jpeg',
        rating: 4.5,
        reviews: 156,
        stock: 60,
      ),
      Product(
        id: '60',
        name: 'Coklat Panas Instan 200gr',
        categoryId: '4',
        categoryName: 'Minuman',
        price: 26000,
        description: 'Coklat panas yang hangat dan nikmat',
        imageUrl:
            'https://images.pexels.com/photos/3957998/pexels-photo-3957998.jpeg',
        rating: 4.6,
        reviews: 189,
        stock: 50,
      ),

      // KATEGORI 5: Roti & Bakery (15 produk)
      Product(
        id: '61',
        name: 'Roti Tawar Putih 1 Loaf',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 28000,
        description: 'Roti tawar putih yang lembut dan segar',
        imageUrl:
            'https://images.pexels.com/photos/3962671/pexels-photo-3962671.jpeg',
        rating: 4.6,
        reviews: 356,
        stock: 50,
      ),
      Product(
        id: '62',
        name: 'Roti Tawar Coklat 1 Loaf',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 32000,
        description: 'Roti tawar dengan rasa coklat yang lezat',
        imageUrl:
            'https://images.pexels.com/photos/3962672/pexels-photo-3962672.jpeg',
        rating: 4.6,
        reviews: 289,
        stock: 40,
      ),
      Product(
        id: '63',
        name: 'Croissant Butter 4 Pcs',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 38000,
        description: 'Croissant berlapis dengan mentega premium',
        imageUrl:
            'https://images.pexels.com/photos/3962673/pexels-photo-3962673.jpeg',
        rating: 4.7,
        reviews: 234,
        stock: 35,
      ),
      Product(
        id: '64',
        name: 'Baguette Perancis 1 Batang',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 35000,
        description: 'Baguette asli perancis yang renyah',
        imageUrl:
            'https://images.pexels.com/photos/3962674/pexels-photo-3962674.jpeg',
        rating: 4.5,
        reviews: 178,
        stock: 30,
      ),
      Product(
        id: '65',
        name: 'Donat Coklat Gula 6 Pcs',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 32000,
        description: 'Donat empuk dengan topping coklat dan gula',
        imageUrl:
            'https://images.pexels.com/photos/3962675/pexels-photo-3962675.jpeg',
        rating: 4.6,
        reviews: 289,
        stock: 60,
      ),
      Product(
        id: '66',
        name: 'Muffin Blueberry 4 Pcs',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 42000,
        description: 'Muffin dengan potongan blueberry segar',
        imageUrl:
            'https://images.pexels.com/photos/3962676/pexels-photo-3962676.jpeg',
        rating: 4.7,
        reviews: 212,
        stock: 25,
      ),
      Product(
        id: '67',
        name: 'Cupcake Vanilla 6 Pcs',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 45000,
        description: 'Cupcake vanilla dengan frosting lembut',
        imageUrl:
            'https://images.pexels.com/photos/3962677/pexels-photo-3962677.jpeg',
        rating: 4.7,
        reviews: 245,
        stock: 30,
      ),
      Product(
        id: '68',
        name: 'Roti Focaccia Olive 1 Loaf',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 38000,
        description: 'Roti focaccia dengan olive dan herbs',
        imageUrl:
            'https://images.pexels.com/photos/3962678/pexels-photo-3962678.jpeg',
        rating: 4.6,
        reviews: 156,
        stock: 20,
      ),
      Product(
        id: '69',
        name: 'Cookies Oatmeal 200gr',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 32000,
        description: 'Cookies oatmeal renyah dan bergizi',
        imageUrl:
            'https://images.pexels.com/photos/3962679/pexels-photo-3962679.jpeg',
        rating: 4.5,
        reviews: 189,
        stock: 50,
      ),
      Product(
        id: '70',
        name: 'Brownies Coklat 250gr',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 35000,
        description: 'Brownies dengan coklat premium yang pekat',
        imageUrl:
            'https://images.pexels.com/photos/3962680/pexels-photo-3962680.jpeg',
        rating: 4.7,
        reviews: 267,
        stock: 40,
      ),
      Product(
        id: '71',
        name: 'Bread Sticks Sesame 150gr',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 22000,
        description: 'Breadsticks dengan taburan sesame',
        imageUrl:
            'https://images.pexels.com/photos/3962681/pexels-photo-3962681.jpeg',
        rating: 4.4,
        reviews: 123,
        stock: 70,
      ),
      Product(
        id: '72',
        name: 'Sourdough Bread 1 Loaf',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 42000,
        description: 'Roti sourdough dengan fermentasi alami',
        imageUrl:
            'https://images.pexels.com/photos/3962682/pexels-photo-3962682.jpeg',
        rating: 4.6,
        reviews: 156,
        stock: 25,
      ),
      Product(
        id: '73',
        name: 'Pain au Chocolat 4 Pcs',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 45000,
        description: 'Pain au chocolat perancis yang lezat',
        imageUrl:
            'https://images.pexels.com/photos/3962683/pexels-photo-3962683.jpeg',
        rating: 4.7,
        reviews: 198,
        stock: 20,
      ),
      Product(
        id: '74',
        name: 'Roti Bakar Gulung 250gr',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 28000,
        description: 'Roti bakar gulung dengan isi variatif',
        imageUrl:
            'https://images.pexels.com/photos/3962684/pexels-photo-3962684.jpeg',
        rating: 4.5,
        reviews: 145,
        stock: 60,
      ),
      Product(
        id: '75',
        name: 'Croissant Coklat 6 Pcs',
        categoryId: '5',
        categoryName: 'Roti & Bakery',
        price: 48000,
        description: 'Croissant dengan isian coklat premium',
        imageUrl:
            'https://images.pexels.com/photos/3962685/pexels-photo-3962685.jpeg',
        rating: 4.7,
        reviews: 234,
        stock: 30,
      ),

      // KATEGORI 6: Rokok (15 produk)
      Product(
        id: '76',
        name: 'Rokok Malboro Red 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 45000,
        description: 'Rokok Marlboro Red dengan filter premium',
        imageUrl:
            'https://images.pexels.com/photos/3962400/pexels-photo-3962400.jpeg',
        rating: 4.5,
        reviews: 234,
        stock: 80,
      ),
      Product(
        id: '77',
        name: 'Rokok Djarum Super 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 35000,
        description: 'Rokok dengan cengkeh pilihan',
        imageUrl:
            'https://images.pexels.com/photos/3962401/pexels-photo-3962401.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 100,
      ),
      Product(
        id: '78',
        name: 'Rokok Gudang Garam Filter 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 38000,
        description: 'Rokok dengan cengkeh aromatis',
        imageUrl:
            'https://images.pexels.com/photos/3962402/pexels-photo-3962402.jpeg',
        rating: 4.5,
        reviews: 178,
        stock: 90,
      ),
      Product(
        id: '79',
        name: 'Rokok Sampoerna Mild 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 36000,
        description: 'Rokok dengan rasa mild yang halus',
        imageUrl:
            'https://images.pexels.com/photos/3962403/pexels-photo-3962403.jpeg',
        rating: 4.4,
        reviews: 134,
        stock: 85,
      ),
      Product(
        id: '80',
        name: 'Rokok Pall Mall Red 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 42000,
        description: 'Rokok dengan cita rasa kuat dan nikmat',
        imageUrl:
            'https://images.pexels.com/photos/3962404/pexels-photo-3962404.jpeg',
        rating: 4.5,
        reviews: 167,
        stock: 75,
      ),
      Product(
        id: '81',
        name: 'Rokok LM Strong 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 38000,
        description: 'Rokok dengan rasa strong dan kuat',
        imageUrl:
            'https://images.pexels.com/photos/3962405/pexels-photo-3962405.jpeg',
        rating: 4.4,
        reviews: 145,
        stock: 70,
      ),
      Product(
        id: '82',
        name: 'Rokok A Mild 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 35000,
        description: 'Rokok dengan filter A yang premium',
        imageUrl:
            'https://images.pexels.com/photos/3962406/pexels-photo-3962406.jpeg',
        rating: 4.3,
        reviews: 123,
        stock: 80,
      ),
      Product(
        id: '83',
        name: 'Rokok Mild Seven Light 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 40000,
        description: 'Rokok dengan rasa light yang menyegarkan',
        imageUrl:
            'https://images.pexels.com/photos/3962407/pexels-photo-3962407.jpeg',
        rating: 4.5,
        reviews: 189,
        stock: 75,
      ),
      Product(
        id: '84',
        name: 'Rokok Winstons Classic 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 42000,
        description: 'Rokok dengan rasa klasik dan konsisten',
        imageUrl:
            'https://images.pexels.com/photos/3962408/pexels-photo-3962408.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 70,
      ),
      Product(
        id: '85',
        name: 'Rokok Bentoel Premium 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 38000,
        description: 'Rokok dengan rasa premium dan halus',
        imageUrl:
            'https://images.pexels.com/photos/3962409/pexels-photo-3962409.jpeg',
        rating: 4.5,
        reviews: 167,
        stock: 65,
      ),
      Product(
        id: '86',
        name: 'Rokok Nexus Silver 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 45000,
        description: 'Rokok dengan rasa silver yang elegan',
        imageUrl:
            'https://images.pexels.com/photos/3962410/pexels-photo-3962410.jpeg',
        rating: 4.5,
        reviews: 178,
        stock: 60,
      ),
      Product(
        id: '87',
        name: 'Rokok Kreteks Djarum 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 35000,
        description: 'Kreteks dengan cengkeh kualitas terbaik',
        imageUrl:
            'https://images.pexels.com/photos/3962411/pexels-photo-3962411.jpeg',
        rating: 4.4,
        reviews: 145,
        stock: 85,
      ),
      Product(
        id: '88',
        name: 'Rokok Claro Premium 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 42000,
        description: 'Rokok dengan rasa claro yang nikmat',
        imageUrl:
            'https://images.pexels.com/photos/3962412/pexels-photo-3962412.jpeg',
        rating: 4.5,
        reviews: 156,
        stock: 70,
      ),
      Product(
        id: '89',
        name: 'Rokok Surya Premium 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 40000,
        description: 'Rokok dengan rasa premium dan aromatik',
        imageUrl:
            'https://images.pexels.com/photos/3962413/pexels-photo-3962413.jpeg',
        rating: 4.4,
        reviews: 134,
        stock: 75,
      ),
      Product(
        id: '90',
        name: 'Rokok Sampoerna Isap 1 Bungkus',
        categoryId: '6',
        categoryName: 'Rokok',
        price: 36000,
        description: 'Rokok dengan isapan yang nikmat',
        imageUrl:
            'https://images.pexels.com/photos/3962414/pexels-photo-3962414.jpeg',
        rating: 4.3,
        reviews: 123,
        stock: 80,
      ),

      // KATEGORI 7: Shampo & Kondisioner (15 produk)
      Product(
        id: '91',
        name: 'Shampo Head & Shoulders 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 32000,
        description: 'Shampo anti ketombe dengan formula efektif',
        imageUrl:
            'https://images.pexels.com/photos/3873913/pexels-photo-3873913.jpeg',
        rating: 4.6,
        reviews: 345,
        stock: 70,
      ),
      Product(
        id: '92',
        name: 'Shampo Pantene Nutrient Blends 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 28000,
        description: 'Shampo dengan nutrisi lengkap untuk rambut sehat',
        imageUrl:
            'https://images.pexels.com/photos/3873914/pexels-photo-3873914.jpeg',
        rating: 4.7,
        reviews: 456,
        stock: 85,
      ),
      Product(
        id: '93',
        name: 'Shampo Sunsilk 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 22000,
        description: 'Shampo untuk rambut lurus berkilau',
        imageUrl:
            'https://images.pexels.com/photos/3873915/pexels-photo-3873915.jpeg',
        rating: 4.5,
        reviews: 234,
        stock: 90,
      ),
      Product(
        id: '94',
        name: 'Shampo Dove Therapy 190ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 35000,
        description: 'Shampo dengan perawatan terapi untuk rambut rusak',
        imageUrl:
            'https://images.pexels.com/photos/3873916/pexels-photo-3873916.jpeg',
        rating: 4.6,
        reviews: 289,
        stock: 60,
      ),
      Product(
        id: '95',
        name: 'Shampo Lifebuoy Total 10 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 26000,
        description: 'Shampo dengan proteksi total untuk rambut sehat',
        imageUrl:
            'https://images.pexels.com/photos/3873917/pexels-photo-3873917.jpeg',
        rating: 4.5,
        reviews: 178,
        stock: 75,
      ),
      Product(
        id: '96',
        name: 'Shampo L\'Oreal Paris 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 45000,
        description: 'Shampo premium dengan formula perancis',
        imageUrl:
            'https://images.pexels.com/photos/3873918/pexels-photo-3873918.jpeg',
        rating: 4.7,
        reviews: 212,
        stock: 40,
      ),
      Product(
        id: '97',
        name: 'Kondisioner Pantene 180ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 28000,
        description: 'Kondisioner untuk merawat rambut kering',
        imageUrl:
            'https://images.pexels.com/photos/3873919/pexels-photo-3873919.jpeg',
        rating: 4.6,
        reviews: 234,
        stock: 70,
      ),
      Product(
        id: '98',
        name: 'Kondisioner Dove 180ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 32000,
        description: 'Kondisioner dengan formula melembabkan',
        imageUrl:
            'https://images.pexels.com/photos/3873920/pexels-photo-3873920.jpeg',
        rating: 4.6,
        reviews: 189,
        stock: 65,
      ),
      Product(
        id: '99',
        name: 'Shampo Clear Men 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 30000,
        description: 'Shampo khusus pria anti ketombe',
        imageUrl:
            'https://images.pexels.com/photos/3873921/pexels-photo-3873921.jpeg',
        rating: 4.5,
        reviews: 156,
        stock: 80,
      ),
      Product(
        id: '100',
        name: 'Shampo Ponds 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 24000,
        description: 'Shampo dengan pelindung alami',
        imageUrl:
            'https://images.pexels.com/photos/3873922/pexels-photo-3873922.jpeg',
        rating: 4.4,
        reviews: 145,
        stock: 75,
      ),
      Product(
        id: '101',
        name: 'Shampo TRESemme 400ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 38000,
        description: 'Shampo dengan keratin untuk rambut halus',
        imageUrl:
            'https://images.pexels.com/photos/3873923/pexels-photo-3873923.jpeg',
        rating: 4.6,
        reviews: 167,
        stock: 50,
      ),
      Product(
        id: '102',
        name: 'Shampo Herbal Essences 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 26000,
        description: 'Shampo herbal untuk rambut alami',
        imageUrl:
            'https://images.pexels.com/photos/3873924/pexels-photo-3873924.jpeg',
        rating: 4.5,
        reviews: 123,
        stock: 70,
      ),
      Product(
        id: '103',
        name: 'Shampo Garnier Botanic 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 34000,
        description: 'Shampo dengan ekstrak tumbuhan alami',
        imageUrl:
            'https://images.pexels.com/photos/3873925/pexels-photo-3873925.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 60,
      ),
      Product(
        id: '104',
        name: 'Shampo Loreal Expert 200ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 42000,
        description: 'Shampo profesional dari salon',
        imageUrl:
            'https://images.pexels.com/photos/3873926/pexels-photo-3873926.jpeg',
        rating: 4.7,
        reviews: 198,
        stock: 45,
      ),
      Product(
        id: '105',
        name: 'Kondisioner Clear Women 180ml',
        categoryId: '7',
        categoryName: 'Shampo & Kondisioner',
        price: 28000,
        description: 'Kondisioner wanita dengan formula khusus',
        imageUrl:
            'https://images.pexels.com/photos/3873927/pexels-photo-3873927.jpeg',
        rating: 4.5,
        reviews: 156,
        stock: 65,
      ),

      // KATEGORI 8: Sabun & Body Care (15 produk)
      Product(
        id: '106',
        name: 'Sabun Lux White Radiance 80gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 12000,
        description: 'Sabun dengan formula pemutih alami',
        imageUrl:
            'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg',
        rating: 4.6,
        reviews: 234,
        stock: 100,
      ),
      Product(
        id: '107',
        name: 'Sabun Lifebuoy Lemon Fresh 75gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 9000,
        description: 'Sabun antibakteri dengan aroma lemon segar',
        imageUrl:
            'https://images.pexels.com/photos/3945684/pexels-photo-3945684.jpeg',
        rating: 4.5,
        reviews: 345,
        stock: 150,
      ),
      Product(
        id: '108',
        name: 'Sabun Dove Beauty Cream 100gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 18000,
        description: 'Sabun dengan krim pelembab kaya',
        imageUrl:
            'https://images.pexels.com/photos/3945685/pexels-photo-3945685.jpeg',
        rating: 4.7,
        reviews: 289,
        stock: 80,
      ),
      Product(
        id: '109',
        name: 'Sabun Dettol Cool 65gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 14000,
        description: 'Sabun antibakteri dengan sensasi cool mendinginkan',
        imageUrl:
            'https://images.pexels.com/photos/3945686/pexels-photo-3945686.jpeg',
        rating: 4.5,
        reviews: 178,
        stock: 90,
      ),
      Product(
        id: '110',
        name: 'Sabun Sunlight Lemon Fresh 75gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 10000,
        description: 'Sabun pembersih dengan aroma lemon yang menyegarkan',
        imageUrl:
            'https://images.pexels.com/photos/3945687/pexels-photo-3945687.jpeg',
        rating: 4.4,
        reviews: 156,
        stock: 120,
      ),
      Product(
        id: '111',
        name: 'Sabun Carex Original 80gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 16000,
        description: 'Sabun antibakteri formula original',
        imageUrl:
            'https://images.pexels.com/photos/3945688/pexels-photo-3945688.jpeg',
        rating: 4.6,
        reviews: 198,
        stock: 85,
      ),
      Product(
        id: '112',
        name: 'Body Lotion Vaseline 200ml',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 35000,
        description: 'Losion tubuh dengan kelembaban 24 jam',
        imageUrl:
            'https://images.pexels.com/photos/3945689/pexels-photo-3945689.jpeg',
        rating: 4.6,
        reviews: 267,
        stock: 50,
      ),
      Product(
        id: '113',
        name: 'Body Lotion Citra 200ml',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 28000,
        description: 'Losion tubuh dengan ekstrak Citra asli',
        imageUrl:
            'https://images.pexels.com/photos/3945690/pexels-photo-3945690.jpeg',
        rating: 4.5,
        reviews: 189,
        stock: 70,
      ),
      Product(
        id: '114',
        name: 'Body Wash Fiesta Fresh 250ml',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 32000,
        description: 'Sabun mandi cair dengan aroma fiesta yang segar',
        imageUrl:
            'https://images.pexels.com/photos/3945691/pexels-photo-3945691.jpeg',
        rating: 4.6,
        reviews: 234,
        stock: 65,
      ),
      Product(
        id: '115',
        name: 'Body Wash Lifebouy 250ml',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 28000,
        description: 'Sabun mandi antibakteri yang menyegarkan',
        imageUrl:
            'https://images.pexels.com/photos/3945692/pexels-photo-3945692.jpeg',
        rating: 4.5,
        reviews: 156,
        stock: 80,
      ),
      Product(
        id: '116',
        name: 'Sabun Cuci Tangan Dettol 250ml',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 22000,
        description: 'Sabun tangan dengan formula antibakteri',
        imageUrl:
            'https://images.pexels.com/photos/3945693/pexels-photo-3945693.jpeg',
        rating: 4.6,
        reviews: 167,
        stock: 75,
      ),
      Product(
        id: '117',
        name: 'Facial Wash Cetaphil 125ml',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 48000,
        description: 'Pembersih wajah dengan formula lembut',
        imageUrl:
            'https://images.pexels.com/photos/3945694/pexels-photo-3945694.jpeg',
        rating: 4.7,
        reviews: 212,
        stock: 40,
      ),
      Product(
        id: '118',
        name: 'Sabun Papaya Herbal 100gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 15000,
        description: 'Sabun herbal dengan ekstrak pepaya',
        imageUrl:
            'https://images.pexels.com/photos/3945695/pexels-photo-3945695.jpeg',
        rating: 4.5,
        reviews: 145,
        stock: 100,
      ),
      Product(
        id: '119',
        name: 'Sabun Belerang 100gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 12000,
        description: 'Sabun belerang untuk perawatan kulit khusus',
        imageUrl:
            'https://images.pexels.com/photos/3945696/pexels-photo-3945696.jpeg',
        rating: 4.4,
        reviews: 123,
        stock: 75,
      ),
      Product(
        id: '120',
        name: 'Sabun Rose Milk 100gr',
        categoryId: '8',
        categoryName: 'Sabun & Body Care',
        price: 16000,
        description: 'Sabun dengan susu murni dan ekstrak bunga mawar',
        imageUrl:
            'https://images.pexels.com/photos/3945697/pexels-photo-3945697.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 70,
      ),

      // KATEGORI 9: Alat Kecantikan (15 produk)
      Product(
        id: '121',
        name: 'Facial Roller Jade 1 Pcs',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 65000,
        description: 'Facial roller batu jade untuk pijat wajah',
        imageUrl:
            'https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg',
        rating: 4.7,
        reviews: 234,
        stock: 35,
      ),
      Product(
        id: '122',
        name: 'Makeup Brush Set 24 Pcs',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 125000,
        description: 'Set lengkap kuas makeup profesional',
        imageUrl:
            'https://images.pexels.com/photos/3807518/pexels-photo-3807518.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 25,
      ),
      Product(
        id: '123',
        name: 'Hair Straightener Profesional',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 185000,
        description: 'Pelurus rambut dengan teknologi ionic',
        imageUrl:
            'https://images.pexels.com/photos/3807519/pexels-photo-3807519.jpeg',
        rating: 4.7,
        reviews: 156,
        stock: 15,
      ),
      Product(
        id: '124',
        name: 'Hair Dryer 2000W Pro',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 225000,
        description: 'Pengering rambut profesional dengan teknologi terbaru',
        imageUrl:
            'https://images.pexels.com/photos/3807520/pexels-photo-3807520.jpeg',
        rating: 4.8,
        reviews: 267,
        stock: 20,
      ),
      Product(
        id: '125',
        name: 'Eyelash Curler Premium',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 45000,
        description: 'Penjepit bulu mata dengan desain ergonomis',
        imageUrl:
            'https://images.pexels.com/photos/3807521/pexels-photo-3807521.jpeg',
        rating: 4.6,
        reviews: 145,
        stock: 50,
      ),
      Product(
        id: '126',
        name: 'Nail Buffer & Shiner Set',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 35000,
        description: 'Set lengkap untuk perawatan kuku',
        imageUrl:
            'https://images.pexels.com/photos/3807522/pexels-photo-3807522.jpeg',
        rating: 4.5,
        reviews: 123,
        stock: 60,
      ),
      Product(
        id: '127',
        name: 'Facial Massage Device',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 95000,
        description: 'Alat pijat wajah elektrik untuk relaksasi',
        imageUrl:
            'https://images.pexels.com/photos/3807523/pexels-photo-3807523.jpeg',
        rating: 4.6,
        reviews: 189,
        stock: 30,
      ),
      Product(
        id: '128',
        name: 'Hair Dryer Ionic Compact',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 145000,
        description: 'Pengering rambut compact dengan teknologi ionic',
        imageUrl:
            'https://images.pexels.com/photos/3807524/pexels-photo-3807524.jpeg',
        rating: 4.6,
        reviews: 167,
        stock: 25,
      ),
      Product(
        id: '129',
        name: 'Eyebrow Trimmer Electric',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 55000,
        description: 'Pemotong alis elektrik yang presisi',
        imageUrl:
            'https://images.pexels.com/photos/3807525/pexels-photo-3807525.jpeg',
        rating: 4.5,
        reviews: 98,
        stock: 40,
      ),
      Product(
        id: '130',
        name: 'Lip Brush Set 10 Pcs',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 42000,
        description: 'Set lengkap kuas untuk makeup bibir',
        imageUrl:
            'https://images.pexels.com/photos/3807526/pexels-photo-3807526.jpeg',
        rating: 4.5,
        reviews: 123,
        stock: 55,
      ),
      Product(
        id: '131',
        name: 'Beauty Blender Sponge 3 Pcs',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 32000,
        description: 'Spon makeup untuk hasil halus sempurna',
        imageUrl:
            'https://images.pexels.com/photos/3807527/pexels-photo-3807527.jpeg',
        rating: 4.6,
        reviews: 178,
        stock: 70,
      ),
      Product(
        id: '132',
        name: 'Electric Facial Cleanser',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 165000,
        description: 'Alat pembersih wajah elektrik yang efektif',
        imageUrl:
            'https://images.pexels.com/photos/3807528/pexels-photo-3807528.jpeg',
        rating: 4.7,
        reviews: 212,
        stock: 20,
      ),
      Product(
        id: '133',
        name: 'Curling Iron Pro 32mm',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 185000,
        description: 'Alat pengikal rambut profesional',
        imageUrl:
            'https://images.pexels.com/photos/3807529/pexels-photo-3807529.jpeg',
        rating: 4.6,
        reviews: 145,
        stock: 18,
      ),
      Product(
        id: '134',
        name: 'Makeup Mirror LED Portable',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 85000,
        description: 'Cermin makeup dengan lampu LED',
        imageUrl:
            'https://images.pexels.com/photos/3807530/pexels-photo-3807530.jpeg',
        rating: 4.6,
        reviews: 156,
        stock: 35,
      ),
      Product(
        id: '135',
        name: 'Professional Scissors Straight',
        categoryId: '9',
        categoryName: 'Alat Kecantikan',
        price: 125000,
        description: 'Gunting profesional untuk perawatan kuku',
        imageUrl:
            'https://images.pexels.com/photos/3807531/pexels-photo-3807531.jpeg',
        rating: 4.5,
        reviews: 134,
        stock: 40,
      ),
    ];
  }
}